/**
 * @file ISAMIBModule.c
 * @author Martin Kostelník (xkoste12)
 * @brief ISA Project 2020: C file implementing dynamically loaded extension to SNMP agent.
 * @version 1.0
 * @date 2020-11-18
 * 
 * @copyright Copyright (c) 2020
 * 
 */

/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include <string.h>
#include <time.h>

#ifdef __linux__
    #include <sys/sysinfo.h>
#endif

#include "ISAMIBModule.h"

// String containing my login
static char loginObj[] = "xkoste12";

// String containing UTC time in RFC 3339 standard format
static char timeObj[35] = "1111-11-11T11:11:11Z";

// Int containing a read-write integer
static int intObj = 0;

// Backup for intObj
static int intObj_backup = 0;

// Int containing the amount of available RAM
static int ramObj = 1024;

/** Initializes the ISAMIBModule module */
void
init_ISAMIBModule(void)
{
    const oid loginObject_oid[] = { 1,3,6,1,3,22,1 };
    const oid timeObject_oid[] = { 1,3,6,1,3,22,2 };
    const oid intObject_oid[] = { 1,3,6,1,3,22,3 };
    const oid ramObject_oid[] = { 1,3,6,1,3,22,4 };

  DEBUGMSGTL(("ISAMIBModule", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("loginObject", handle_loginObject,
                               loginObject_oid, OID_LENGTH(loginObject_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("timeObject", handle_timeObject,
                               timeObject_oid, OID_LENGTH(timeObject_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("intObject", handle_intObject,
                               intObject_oid, OID_LENGTH(intObject_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("ramObject", handle_ramObject,
                               ramObject_oid, OID_LENGTH(ramObject_oid),
                               HANDLER_CAN_RONLY
        ));
}

/**
 * @brief Handler function for loginObject specified in MIB.
 */
int
handle_loginObject(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, loginObj, strlen(loginObj));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_loginObject\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

/**
 * @brief Handler function for timeObject specified in MIB.
 */
int
handle_timeObject(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */

    // Get UTC Time
    time_t rtime;
    struct tm* t;

    // Get time since last epoch
    time(&rtime);

    // Get UTC time (almost)
    t = gmtime(&rtime);

    // Create RFC3339 timestamp
    sprintf(timeObj,
            "%d-%02d-%02dT%02d:%02d:%02dZ",
            t->tm_year + 1900,
            t->tm_mon + 1,
            t->tm_mday,
            t->tm_hour,
            t->tm_min,
            t->tm_sec);
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, timeObj, strlen(timeObj));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_timeObject\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

/**
 * @brief Handler function for intObject specifed in MIB.
 */
int
handle_intObject(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER, &intObj, sizeof(intObj));
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;

        case MODE_SET_RESERVE2:
            // Set Backup
            intObj_backup = intObj;
            break;

        case MODE_SET_FREE:
            break;

        case MODE_SET_ACTION:
            // Change value
            intObj = *(requests->requestvb->val.integer);
            break;

        case MODE_SET_COMMIT:
            break;

        case MODE_SET_UNDO:
            // Restore backup
            intObj = intObj_backup;
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_intObject\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

/**
 * @brief Handler function for ramObject specified in MIB.
 */
int
handle_ramObject(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */

    #ifdef __linux__
        struct sysinfo i;
        
        // Get sysinfo
        sysinfo(&i);
        ramObj = i.totalram >> 20; // ramObj = i.totalram / 2^20 (get MB)
    #else
        ramObj = 0;
    #endif

    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER, &ramObj, sizeof(ramObj));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_ramObject\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
